// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: commands.sql

package storage

import (
	"context"
)

const createSAMLRequest = `-- name: CreateSAMLRequest :exec
INSERT INTO saml_requests (id, relay_state, sp_acs_url, created_at, expires_at)
VALUES (?, ?, ?, ?, ?)
`

type CreateSAMLRequestParams struct {
	ID         string `json:"id"`
	RelayState string `json:"relay_state"`
	SpAcsUrl   string `json:"sp_acs_url"`
	CreatedAt  int64  `json:"created_at"`
	ExpiresAt  int64  `json:"expires_at"`
}

func (q *Queries) CreateSAMLRequest(ctx context.Context, arg CreateSAMLRequestParams) error {
	_, err := q.db.ExecContext(ctx, createSAMLRequest,
		arg.ID,
		arg.RelayState,
		arg.SpAcsUrl,
		arg.CreatedAt,
		arg.ExpiresAt,
	)
	return err
}

const deleteExpiredRequests = `-- name: DeleteExpiredRequests :exec
DELETE FROM saml_requests WHERE expires_at < ?
`

func (q *Queries) DeleteExpiredRequests(ctx context.Context, expiresAt int64) error {
	_, err := q.db.ExecContext(ctx, deleteExpiredRequests, expiresAt)
	return err
}

const deleteSAMLRequest = `-- name: DeleteSAMLRequest :exec
DELETE FROM saml_requests WHERE id = ?
`

func (q *Queries) DeleteSAMLRequest(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteSAMLRequest, id)
	return err
}
