// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package storage

type SamlRequest struct {
	ID         string `json:"id"`
	RelayState string `json:"relay_state"`
	SpAcsUrl   string `json:"sp_acs_url"`
	CreatedAt  int64  `json:"created_at"`
	ExpiresAt  int64  `json:"expires_at"`
}

type Session struct {
	SessionIndex string `json:"session_index"`
	NameID       string `json:"name_id"`
	IDToken      string `json:"id_token"`
	SpEntityID   string `json:"sp_entity_id"`
	CreatedAt    int64  `json:"created_at"`
	ExpiresAt    int64  `json:"expires_at"`
}
