// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package storage

import (
	"context"
)

type Querier interface {
	// Queries for sqlc
	CreateSAMLRequest(ctx context.Context, arg CreateSAMLRequestParams) error
	DeleteExpiredRequests(ctx context.Context, expiresAt int64) error
	DeleteSAMLRequest(ctx context.Context, id string) error
	GetSAMLRequest(ctx context.Context, id string) (SamlRequest, error)
}

var _ Querier = (*Queries)(nil)
