// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package storage

import (
	"context"
)

const getSAMLRequest = `-- name: GetSAMLRequest :one
SELECT id, relay_state, sp_acs_url, created_at, expires_at
FROM saml_requests
WHERE id = ?
`

func (q *Queries) GetSAMLRequest(ctx context.Context, id string) (SamlRequest, error) {
	row := q.db.QueryRowContext(ctx, getSAMLRequest, id)
	var i SamlRequest
	err := row.Scan(
		&i.ID,
		&i.RelayState,
		&i.SpAcsUrl,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}
